name: smallbiznis

services:
  controlplane:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: cmd/controlplane
        OUTPUT_NAME: controlplane
    container_name: controlplane
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cmd/controlplane/config.yaml:/app/config.yaml

  ledger:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: cmd/ledger
        OUTPUT_NAME: ledger
    container_name: ledger
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cmd/ledger/config.yaml:/app/config.yaml

  rule:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: cmd/rule
        OUTPUT_NAME: rule
    container_name: rule
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cmd/rule/config.yaml:/app/config.yaml

  loyalty:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: cmd/loyalty
        OUTPUT_NAME: loyalty
    container_name: loyalty
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cmd/loyalty/config.yaml:/app/config.yaml

  transaction:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: cmd/transaction
        OUTPUT_NAME: transaction
    container_name: transaction
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cmd/transaction/config.yaml:/app/config.yaml

  # inventory:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       SERVICE_PATH: cmd/inventory
  #       OUTPUT_NAME: inventory
  #   container_name: inventory
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./cmd/inventory/config.yaml:/app/config.yaml

  voucher:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: cmd/voucher
        OUTPUT_NAME: voucher
    container_name: voucher
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cmd/voucher/config.yaml:/app/config.yaml

  task:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_PATH: cmd/task
        OUTPUT_NAME: task
    container_name: task
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cmd/task/config.yaml:/app/config.yaml

networks:
  default:
    name: infra_default
    external: true